import React from 'react';
import '../styles/Projects.css';

const Projects = () => {
    return (
        <div className="projects-container">
            <div className="project-card">
                <h2 className="project-title">Organic Grocery "SEED" Website</h2>
                <p className="project-description">I had co-developed a grocery website using React.js, node.js, express and graphQL. </p>
            </div>
            <div className="project-card">
                <h2 className="project-title">Minecraft Maze Generation</h2>
                <p className="project-description">I created a Minecraft mod that generates mazes within the game. The mod uses a breadth-first search algorithm to create complex and challenging mazes.
                    The mazes could be generated using user input or randomly generated by the use of random pattern generation. In this project, I was tasked with the player's abilities while the maze was active. As the player,
                    I should be able to teleport into the maze as well as solve the maze using a path solver algorithm. 
                </p>
            </div>
        </div>
    );
};

export default Projects;